language: python
python:
- '3.7'
env:
  global:
    - SECRET_KEY="$SECRET_KEY"
    - DB_HOST="localhost"
    - DB_USER="travis"
    - DB_PASSWORD="test"
services:
- mongodb
- docker
install:
- pip install -r backend/requirements.txt
before_script:
  - mongo blockchain_db --eval 'db.createUser({user:"travis",pwd:"test",roles:["clusterAdmin"]});'
script:
- coverage run -m --source=backend/app unittest && coverage report -m
after_success:
- coveralls
deploy:
  provider: script
  script: bash docker_deploy
  on:
    branch: master
