language: python
python:
- '3.7'
env: # Test an init node, then any other subsequent node
- INIT_NODE_IP=""
- INIT_NODE_IP = "localhost:5001
services:
- mongodb
install:
- pip install -r backend/requirements.txt
before_script:
  - sleep 15  # MongoDB does not immediately accept connections remedy
  - mongo mydb_test --eval 'db.createUser({user:"tester",pwd:"testing",roles:["readWrite", "dbAdmin"]});'
script:
- coverage run -m --source=backend/app unittest && coverage report -m
after_success:
- coveralls
