# *** AWS Graviton2 build CPU support configs **
os: linux
dist: focal
group: edge
arch: arm64-graviton2
compiler: clang
# ****
language: python
python:
  - '3.7'
env:
  global:
    - TEST="testing"
    - FLASK_ENV="development"
    - HOST_IP="localhost"
    - HOST_PORT="5000"
    - MONGO_DB_HOST="localhost"
    - MONGO_DB_USER="travis"
    - MONGO_DB_PASSWORD="test"
    - REDIS_DB_HOST="localhost"
    - REDIS_DB_USER=""
    - REDIS_DB_PASSWORD=""
  jobs:
    - INIT_NODE_IP='localhost:5001'
    - INIT_NODE_IP=
services:
  - mongodb
  - redis
  - docker
install:
  - pip install -r backend/src/requirements.txt
before_script:
  - mongo test_db --eval 'db.createUser({user:"travis",pwd:"test", roles:["readWrite"]});'
script:
  - clang --version
  - coverage run -m --source=src/app unittest && coverage report -m
after_success:
  - coveralls
deploy:
  provider: script
  script: bash docker_deploy
  on:
    branch: master
