#!/bin/bash
docker build -t "$DOCKER_REPO"/blockchain-backend backend/
docker build -t "$DOCKER_REPO"/blockchain-frontend frontend/
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push "$DOCKER_REPO"/blockchain-backend:latest
docker push "$DOCKER_REPO"/blockchain-frontend:latest
docker logout
