#!/bin/bash
export FLASK_ENV=development
export SECRET_KEY=2c635640-c8c4-4f0d-8790-e6008d8eecce
export API_KEY=0f2372ebbfee3231a9ddf5db4bf505ddbc5ad6d90c665e856baf224a8960cfa8

export INIT_NODE_IP=
export DB_HOST=localhost

export MONGO_DB_USER=user1
export MONGO_DB_PASSWORD=password1

export REDIS_DB_USER=default
export REDIS_DB_PASSWORD=8fea17c9-8b3c-4c1a-abd0-0f17f7e415ec

flask run
