version: "3"

# Add secrets, volumes and proxy server in production

services:
    mongo_db:
        image: mongo:4.2.5
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                condition: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: node1
            MONGO_INITDB_ROOT_PASSWORD: node1#Password

    blockchain_app:
        image: kennethmacharia/blockchain-backend:latest
        ports:
            - "8090:5000"
        depends_on:
            - mongo_db
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                condition: on-failure
                delay: 5s
        environment:
            INIT_NODE_IP:
            FLASK_ENV: development
            SECRET_KEY: <Enter hub initialization key>
            DB_HOST: mongo_db
            DB_USER: node1
            DB_PASSWORD: node1#Password

    visualizer:
        image: dockersamples/visualizer
        ports:
            - "8080:8080"
        stop_grace_period: 30s
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
