version: "3.3"

# Add secrets, volumes and proxy server in production

services:
    mongo_db_2:
        image: mongo:4.2.8
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                condition: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: d7950fda-5858-4515-ae22-1ba28591f210

    redis_db_2:
        image: redis:6.0.3
        configs:
            - source: config_file
              target: /usr/local/etc/redis.conf
        command: [ "redis-server", "--appendonly", "yes"]
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure

    blockchain_app_2:
        build: ../../backend
        image: kennethmacharia/blockchain-backend:latest
        ports:
            - 8091:5000
        depends_on:
            - mongo_db_2
            - redis_db_2
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                condition: on-failure
                delay: 5s
        environment:
            PYTHONUNBUFFERED: 1
            FLASK_ENV: development
            INIT_NODE_IP: 192.168.100.208:8090
            SECRET_KEY: 2c635640-c8c4-4f0d-8790-e6008d8eecce
            MONGO_DB_HOST: mongo_db_2
            MONGO_DB_USER: root
            MONGO_DB_PASSWORD: d7950fda-5858-4515-ae22-1ba28591f210
            REDIS_DB_HOST: redis_db_2
            REDIS_DB_USER: default
            REDIS_DB_PASSWORD: 8fea17c9-8b3c-4c1a-abd0-0f17f7e415ec

configs:
    config_file: # Change host config file location
        file: /usr/local/etc/redis.conf
