---
- hosts: tag_Ansible_swarm_leader
  become: true
  gather_facts: true
  tasks:
    - name: Initliaize swarm cluster
      shell: docker swarm init

    - name: Save manager join script
      shell: "out=$( docker swarm join-token manager ) && val=${out#*:} && echo $val > manager_join_src.sh"

    - name: Save worker join script
      shell: "out=$( docker swarm join-token worker ) && val=${out#*:} && echo $val > worker_join_src.sh"
