---
- hosts: localhost
  gather_facts: true
  tasks:
    - name: Copy orchestration file to swarm leader
      shell: "scp ../orchestrate/deploy_app_init.yml azureuser@40.114.231.136:/home/azureuser/"
