---
- hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install Docker
      shell: curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh && usermod -aG docker azureuser

    - name: Copy Redis config file
      shell: wget https://api.onedrive.com/v1.0/shares/u!aHR0cHM6Ly8xZHJ2Lm1zL3UvcyFBa0VISDVMN0pmSGRobkp5QnRDSkZCQTVCU2dXP2U9bGYzMG1a/root/content -O redis.conf
