---
- hosts: tag_Ansible_swarm_leader
  become: true
  gather_facts: true
  tasks:
    - name: Deploy app to swarm cluster
      shell: "docker stack deploy -c /home/azureuser/start_app.yml blockchain"
